apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: simple-time-service
          image: arpitha2025/webapp:SimpleTimeService-v1
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: appuser
          

---
apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 8080
